proxy:
  image: nginx:1.13
  ports:
    - "8080:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
    - app:app
app:
  image: node:9
  volumes:
    - ./index.js:/index.js
  command: node index.js
  expose:
    - "8081"
  ports:
    - "8081:8081"
 
